// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Transaction struct {
	ID                 uuid.UUID       `json:"id"`
	TransactionValue   sql.NullFloat64 `json:"transaction_value"`
	ProductDescription sql.NullString  `json:"product_description"`
	CardNumber         sql.NullInt64   `json:"card_number"`
	NameInCard         sql.NullString  `json:"name_in_card"`
	CardExpirationDate sql.NullTime    `json:"card_expiration_date"`
	Cvv                sql.NullInt32   `json:"cvv"`
}
